// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReliantParkingGilberto.Entities;

namespace ReliantParkingGilberto.Migrations
{
    [DbContext(typeof(RentalDbContext))]
    partial class RentalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ReliantParkingGilberto.Entities.Resident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResidentialPropertyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResidentialPropertyId");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("ReliantParkingGilberto.Entities.ResidentialProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ResidentialPropertyTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResidentialPropertyTypeId");

                    b.ToTable("ResidentialProperties");
                });

            modelBuilder.Entity("ReliantParkingGilberto.Entities.ResidentialPropertyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ResidentialPropertyTypes");
                });

            modelBuilder.Entity("ReliantParkingGilberto.Entities.Resident", b =>
                {
                    b.HasOne("ReliantParkingGilberto.Entities.ResidentialProperty", "ResidentialProperty")
                        .WithMany()
                        .HasForeignKey("ResidentialPropertyId");

                    b.Navigation("ResidentialProperty");
                });

            modelBuilder.Entity("ReliantParkingGilberto.Entities.ResidentialProperty", b =>
                {
                    b.HasOne("ReliantParkingGilberto.Entities.ResidentialPropertyType", "ResidentialPropertyType")
                        .WithMany()
                        .HasForeignKey("ResidentialPropertyTypeId");

                    b.Navigation("ResidentialPropertyType");
                });
#pragma warning restore 612, 618
        }
    }
}
